# Generated by Django 5.2.5 on 2025-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featuredproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='featured/')),
                ('price', models.CharField(max_length=20)),
                ('old_price', models.CharField(blank=True, max_length=20, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
