# Generated by Django 5.2.5 on 2025-09-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_electronicsproduct_delete_electronicproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsproduct',
            name='old_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsproduct',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
