# Generated by Django 5.2.5 on 2025-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_electronicsproduct_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsproduct',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
