# Generated by Django 5.2.5 on 2025-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_electronicsproduct_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsproduct',
            name='old_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsproduct',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
