# Generated by Django 5.2.5 on 2025-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_electronicsproduct_old_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDecorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home_decor/')),
                ('price', models.CharField(max_length=20)),
                ('old_price', models.CharField(blank=True, max_length=20, null=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
