# Generated by Django 5.2.5 on 2025-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homedecorproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Font Awesome icon class, e.g., fa-couch', max_length=50)),
                ('products', models.PositiveIntegerField(default=0, help_text='Number of products in this category')),
            ],
        ),
    ]
