# Generated by Django 5.2.5 on 2025-09-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='customers/')),
                ('review', models.TextField()),
                ('rating', models.FloatField(default=5.0, help_text='Rating out of 5 (e.g., 4.5)')),
                ('time', models.CharField(help_text="e.g., '2 days ago'", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('icon', models.CharField(help_text='Font Awesome class (e.g., fa-users)', max_length=100)),
            ],
        ),
    ]
