# Generated by Django 5.2.5 on 2025-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome class (e.g., fa-shipping-fast)', max_length=100)),
            ],
            options={
                'verbose_name': 'Why Choose Tijaar Feature',
                'verbose_name_plural': 'Why Choose Tijaar Features',
                'ordering': ['id'],
            },
        ),
    ]
