# Generated by Django 5.2.5 on 2025-09-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_whyfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short badge title (e.g., Flash Sale)', max_length=100)),
                ('sale', models.CharField(help_text='Main offer heading (e.g., Up to 50% Off)', max_length=100)),
                ('discount', models.CharField(help_text='Highlight discount text (e.g., Today Only)', max_length=100)),
                ('description', models.TextField(help_text='Brief offer description')),
                ('days', models.PositiveIntegerField(default=0)),
                ('hours', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(help_text='Upload offer image', upload_to='offers/')),
            ],
            options={
                'verbose_name': 'Special Offer',
                'verbose_name_plural': 'Special Offers',
                'ordering': ['-id'],
            },
        ),
    ]
