# Generated by Django 5.2.5 on 2025-09-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_wishlist_and_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.featuredproduct'),
            preserve_default=False,
        ),
    ]
